# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Frank-Zhu'
description:      '爱生活、爱分享、想做一个真正属于自己的APP'
url:              'http://frank-zhu.github.io'
baseurl:          ''
logo:             '/content/images/me.png'

author:
  name:           'Frank Zhu'
  url:            'https://github.com/Frank-Zhu'
  email: 		  'zhuwenwu2008@gmail.com'
paginate:         5


disqus_shortname: frank

github:
  repo:           'https://github.com/Frank-Zhu/Frank-Zhu.github.io'

gems:
   - jekyll-sitemap

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
  syntax_highlighter: rouge
